// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHbI7hP2cF2TRon8G-e6P51xF85htzIVE',
    appId: '1:787052587038:web:9053a7fc1362f24590e60f',
    messagingSenderId: '787052587038',
    projectId: 'freight-f1b06',
    authDomain: 'freight-f1b06.firebaseapp.com',
    storageBucket: 'freight-f1b06.firebasestorage.app',
    measurementId: 'G-2E85N394E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5l1NZRDjuhy2PyfNpDqTioqxtanOAA6c',
    appId: '1:787052587038:android:a0290cc871e9d51990e60f',
    messagingSenderId: '787052587038',
    projectId: 'freight-f1b06',
    storageBucket: 'freight-f1b06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYX-M4pYUeh8FJ8EBYgdDKJlDsVAy_e_s',
    appId: '1:787052587038:ios:31a8d9a70894f93a90e60f',
    messagingSenderId: '787052587038',
    projectId: 'freight-f1b06',
    storageBucket: 'freight-f1b06.firebasestorage.app',
    iosBundleId: 'com.example.freightapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYX-M4pYUeh8FJ8EBYgdDKJlDsVAy_e_s',
    appId: '1:787052587038:ios:31a8d9a70894f93a90e60f',
    messagingSenderId: '787052587038',
    projectId: 'freight-f1b06',
    storageBucket: 'freight-f1b06.firebasestorage.app',
    iosBundleId: 'com.example.freightapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHbI7hP2cF2TRon8G-e6P51xF85htzIVE',
    appId: '1:787052587038:web:4af84d65bb42dc9690e60f',
    messagingSenderId: '787052587038',
    projectId: 'freight-f1b06',
    authDomain: 'freight-f1b06.firebaseapp.com',
    storageBucket: 'freight-f1b06.firebasestorage.app',
    measurementId: 'G-YQE4VDSXZK',
  );
}
